export default [
		{ id: 'BA', tags: ['Business Analyst', 'BA']},
		{ id: 'CSS', tags: ['CSS']},
		{ id: 'Chrome', tags: ['Google Chrome', 'Chrome']},
		{ id: 'DevTools', tags: ['Chrome DevTools', 'DevTools']},
		{ id: 'Firefox', tags: ['Firefox']},
		{ id: 'GitHub', tags: ['GitHub']},
		{ id: 'HTML', tags: ['HTML']},
		{ id: 'IE', tags: ['Internet Explorer', 'IE']},
		{ id: 'Internet', tags: ['Internet']},
		{ id: 'Java', tags: ['Java']},
		{ id: 'JavaScript', tags: ['JavaScript', 'JS']},
		{ id: 'Linux', tags: ['Linux']},
		{ id: 'Mac', tags: ['Mac']},
		{ id: 'Next', tags: ['Next']},
		{ id: 'Opera', tags: ['Opera']},
		{ id: 'Origami', tags: ['Origami']},
		{ id: 'PHP', tags: ['PHP']},
		{ id: 'PM', tags: ['Project Manager', 'PM']},
		{ id: 'Python', tags: ['Python']},
		{ id: 'Ruby', tags: ['Ruby']},
		{ id: 'Safari', tags: ['Safari']},
		{ id: 'Sass', tags: ['Sass']},
		{ id: 'UX', tags: ['User Experience', 'UX']},
		{ id: 'Windows', tags: ['Windows']},
		{ id: 'agile', tags: ['agile']},
		{ id: 'app', tags: ['app']},
		{ id: 'browser', tags: ['browser']},
		{ id: 'bug', tags: ['bug', 'defect']},
		{ id: 'code-review', tags: ['code review']},
		{ id: 'code', tags: ['code', 'program']},
		{ id: 'communications', tags: ['communications', 'comms']},
		{ id: 'debug', tags: ['debug']},
		{ id: 'demo', tags: ['demonstration', 'demo']},
		{ id: 'deploy', tags: ['deploy']},
		{ id: 'design', tags: ['design', 'designer']},
		{ id: 'develop', tags: ['develop', 'developer']},
		{ id: 'devops', tags: ['devops']},
		{ id: 'engineer', tags: ['engineer']},
		{ id: 'hardware', tags: ['hardware']},
		{ id: 'issue', tags: ['issue']},
		{ id: 'labs', tags: ['labs']},
		{ id: 'launch', tags: ['launch']},
		{ id: 'lawyer', tags: ['lawyer']},
		{ id: 'legal', tags: ['legal']},
		{ id: 'membership', tags: ['membership']},
		{ id: 'mobile-app', tags: ['mobile app']},
		{ id: 'paywall', tags: ['paywall']},
		{ id: 'platform', tags: ['platform']},
		{ id: 'prototype', tags: ['prototype']},
		{ id: 'pull-request', tags: ['pull request', 'PR']},
		{ id: 'release', tags: ['release']},
		{ id: 'software', tags: ['software']},
		{ id: 'stream', tags: ['stream']},
		{ id: 'technology', tags: ['technology']},
		{ id: 'tester', tags: ['test', 'tester']},
		{ id: 'web-app', tags: ['web app']},
		{ id: 'web', tags: ['web']},
		{ id: 'webpage', tags: ['webpage']}
]
